name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    - name: Install dependencies
      run: |
        pip install pyshark
        pip install paramiko
        ls -la
        cd /usr/lib/python3/dist-packages
        sudo git clone https://github.com/jbardin/scp.py
        sudo mv scp.py scp
        ls -la
        cd
        ls -la



        #import sys
        #print(sys.path)


    - name: Run tests
      run: python3 tests/agent_advert.py
     # run: python3 ~/mip/tests/agent_advert.py
