name: mip CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # runs-on: [self-hosted, linux, x64, gpu]

    steps:
    - uses: actions/checkout@v3
    - name: Configure Virtual Machines
      run: python3 /tests/configure_vms.py
    
    - name: Run Agent Advert test
      run: python3 tests/agent_advert.py
    - name: Run Registration Request test
      run: python3 tests/registration_request.py
