name: mip CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # runs-on: [self-hosted, linux, x64, gpu]

    steps:
    - uses: actions/checkout@v3
    - name: Configure Virtual Machines
      run: python3 tests/configure_VMs.py
    #- name: Run Agent Advert test
     # run: python3 tests/agent_advert.py
    #- name: Run Mobile Node Registration Request test
     # run: python3 tests/mobile_node_registration_request.py    
    - name: Run Home Agent Registration Request test
      run: python3 tests/home_agent_registration_request.py
    #- name: Run Home Agent Registration Reply test
     # run: python3 tests/home_agent_registration_reply.py
    #- name: Run Foreign Agent Registration Reply test
    #  run: python3 tests/foreign_agent_registration_reply.py